### ISSUE TITLE
using this image on OSX?

### ISSUE THREAD

**Issue by KyleChamberlin** [tizonia/docker-tizonia#3]
would it be feasible to use this docker image running on docker with an OSK host? I presume that if I install pulse-audio (there appears to be a homebrew package for this) I could potential bind the socket?

Any direction is appreciated

**Comment by tizonia** [comment]
@KyleChamberlin : 

Sorry for the late reply on this. I have to admit that I have not run the image for a while, and it is in need of a refresh to get it to run the latest version of Tizonia. I would be more than happy to accept PRs for this though.

Unfortunately, I cannot answer your question about OSX host, since I've only tested it on Linux hosts.

**Comment by matthewarmand** [comment]
@KyleChamberlin 

I just merged https://github.com/tizonia/docker-tizonia/pull/8 which adds to the README some helpful instructions for using this on Mac machines. The `docker-tizonia` helper script has also been enhanced to recognize Mac host machines and behave accordingly. Give that a go along with the [latest image available on Dockerhub](https://hub.docker.com/r/tizonia/docker-tizonia), and that should work for you.
